type Yutai = {
  id: string;
  code: string;
  name: string;
  brands: string[];
  categories: string[];
  lifestyleTags: string[];
  minShares: number;
  approxInvestment: number;
  annualValue: number;
  yieldPercent: number;
  description: string;
  rightsMonths: number[];
};

export const YUTAI_LIST: Yutai[] = [
  // ── EC / 通信 ──────────────────────────────────────────────
  {
    id: "4755",
    code: "4755",
    name: "楽天グループ",
    brands: ["楽天市場", "楽天モバイル", "楽天カード", "楽天トラベル", "楽天ペイ", "楽天銀行", "楽天証券"],
    categories: ["EC", "通信"],
    lifestyleTags: ["ネットショッピング派", "キャッシュレス派", "旅行好き"],
    minShares: 100,
    approxInvestment: 90000,
    annualValue: 3000,
    yieldPercent: 3.3,
    description: "楽天キャッシュ3,000円分",
    rightsMonths: [12],
  },
  {
    id: "4689",
    code: "4689",
    name: "LINEヤフー",
    brands: ["Yahoo!ショッピング", "PayPay", "Yahoo!トラベル", "LINEギフト", "ヤフオク!"],
    categories: ["EC", "通信"],
    lifestyleTags: ["ネットショッピング派", "キャッシュレス派", "フリマ利用派"],
    minShares: 100,
    approxInvestment: 40000,
    annualValue: 2000,
    yieldPercent: 5.0,
    description: "PayPayポイント2,000円分(3月・9月各1,000円分)",
    rightsMonths: [3, 9],
  },
  {
    id: "9433",
    code: "9433",
    name: "KDDI",
    brands: ["au", "UQ mobile", "au PAY", "au PAYマーケット", "povo"],
    categories: ["通信"],
    lifestyleTags: ["auユーザー", "キャッシュレス派"],
    minShares: 100,
    approxInvestment: 480000,
    annualValue: 5000,
    yieldPercent: 1.0,
    description: "カタログギフト5,000円相当(5年以上継続保有で6,000円相当に増額)",
    rightsMonths: [3],
  },
  {
    id: "9434",
    code: "9434",
    name: "ソフトバンク",
    brands: ["SoftBank", "Y!mobile", "PayPay", "LINEMO"],
    categories: ["通信"],
    lifestyleTags: ["ソフトバンクユーザー", "キャッシュレス派"],
    minShares: 100,
    approxInvestment: 200000,
    annualValue: 1000,
    yieldPercent: 0.5,
    description: "PayPayポイント1,000円分",
    rightsMonths: [3],
  },

  // ── 外食(ファミリー系) ────────────────────────────────────
  {
    id: "3197",
    code: "3197",
    name: "すかいらーくHD",
    brands: ["ガスト", "バーミヤン", "ジョナサン", "しゃぶ葉", "夢庵", "から好し", "むさしの森珈琲"],
    categories: ["外食"],
    lifestyleTags: ["外食月3回以上", "ファミリー外食", "子育て中"],
    minShares: 100,
    approxInvestment: 210000,
    annualValue: 6000,
    yieldPercent: 2.9,
    description: "食事優待カード6,000円分(3月・9月各3,000円分)",
    rightsMonths: [3, 9],
  },
  {
    id: "7616",
    code: "7616",
    name: "コロワイド",
    brands: ["牛角", "かっぱ寿司", "甘太郎", "ステーキ宮", "フレッシュネスバーガー", "大戸屋"],
    categories: ["外食"],
    lifestyleTags: ["外食月3回以上", "焼肉好き", "回転寿司派"],
    minShares: 200,
    approxInvestment: 360000,
    annualValue: 10000,
    yieldPercent: 2.8,
    description: "グループ飲食代ポイント年間10,000ポイント(200株・3月・9月各5,000ポイント付与)",
    rightsMonths: [3, 9],
  },
  {
    id: "9936",
    code: "9936",
    name: "王将フードサービス",
    brands: ["餃子の王将"],
    categories: ["外食"],
    lifestyleTags: ["外食月3回以上", "コスパ重視"],
    minShares: 100,
    approxInvestment: 800000,
    annualValue: 3000,
    yieldPercent: 0.4,
    description: "食事優待券500円×6枚(年間3,000円分)",
    rightsMonths: [3],
  },
  {
    id: "7581",
    code: "7581",
    name: "サイゼリヤ",
    brands: ["サイゼリヤ"],
    categories: ["外食"],
    lifestyleTags: ["外食月3回以上", "コスパ重視", "ファミリー外食"],
    minShares: 100,
    approxInvestment: 350000,
    annualValue: 2000,
    yieldPercent: 0.6,
    description: "食事優待券500円×4枚(年間2,000円分)",
    rightsMonths: [8],
  },

  // ── 外食(カフェ・軽食系) ──────────────────────────────────
  {
    id: "3087",
    code: "3087",
    name: "ドトール日レスHD",
    brands: ["ドトールコーヒー", "星乃珈琲店", "エクセルシオール カフェ", "ル・パン神戸北野"],
    categories: ["外食"],
    lifestyleTags: ["カフェ派", "コーヒー好き", "在宅ワーク"],
    minShares: 100,
    approxInvestment: 220000,
    annualValue: 3000,
    yieldPercent: 1.4,
    description: "優待カード3,000円分(ドトール・星乃珈琲等グループ全店で使用可)",
    rightsMonths: [2],
  },
  {
    id: "3395",
    code: "3395",
    name: "サンマルクHD",
    brands: ["サンマルクカフェ", "ベーカリーレストランサンマルク", "鎌倉パスタ", "THE 3rd Burger"],
    categories: ["外食"],
    lifestyleTags: ["カフェ派", "パン好き", "ファミリー外食"],
    minShares: 100,
    approxInvestment: 140000,
    annualValue: 4000,
    yieldPercent: 2.9,
    description: "グループ飲食代20%割引優待券(利用回数制限なし、年間推定4,000円相当)",
    rightsMonths: [3],
  },
  {
    id: "3387",
    code: "3387",
    name: "クリエイト・レストランツHD",
    brands: ["磯丸水産", "SFPダイニング", "SIZZLER", "串くら"],
    categories: ["外食"],
    lifestyleTags: ["外食月3回以上", "居酒屋派"],
    minShares: 100,
    approxInvestment: 110000,
    annualValue: 4000,
    yieldPercent: 3.6,
    description: "食事優待券2,000円分×年2回=4,000円分",
    rightsMonths: [2, 8],
  },

  // ── ファッション ──────────────────────────────────────────
  {
    id: "8011",
    code: "8011",
    name: "三陽商会",
    brands: ["MACKINTOSH PHILOSOPHY", "23区", "自由区", "組曲", "ICB"],
    categories: ["ファッション"],
    lifestyleTags: ["ファッション好き", "アパレル高頻度利用"],
    minShares: 100,
    approxInvestment: 80000,
    annualValue: 5000,
    yieldPercent: 6.3,
    description: "自社商品30%割引優待(年間利用上限あり、推定年間5,000円相当)",
    rightsMonths: [2],
  },
  {
    id: "7606",
    code: "7606",
    name: "ユナイテッドアローズ",
    brands: ["UNITED ARROWS", "BEAUTY & YOUTH UNITED ARROWS", "COEN", "green label relaxing"],
    categories: ["ファッション"],
    lifestyleTags: ["ファッション好き", "セレクトショップ派"],
    minShares: 100,
    approxInvestment: 150000,
    annualValue: 6000,
    yieldPercent: 4.0,
    description: "自社商品15%割引優待(3月・9月各優待券付与、年間推定6,000円相当)",
    rightsMonths: [3, 9],
  },
  {
    id: "3608",
    code: "3608",
    name: "TSI HD",
    brands: ["MARGARET HOWELL", "nano・universe", "NATURAL BEAUTY BASIC", "PROPORTION BODY DRESSING"],
    categories: ["ファッション"],
    lifestyleTags: ["ファッション好き", "セレクトショップ派"],
    minShares: 100,
    approxInvestment: 70000,
    annualValue: 5000,
    yieldPercent: 7.1,
    description: "自社グループ商品20%割引優待(2月・8月付与)",
    rightsMonths: [2, 8],
  },
  {
    id: "2792",
    code: "2792",
    name: "ハニーズHD",
    brands: ["Honeys", "CO-EX", "Colza"],
    categories: ["ファッション"],
    lifestyleTags: ["ファッション好き", "コスパ重視"],
    minShares: 100,
    approxInvestment: 110000,
    annualValue: 5000,
    yieldPercent: 4.5,
    description: "自社商品5,000円分買い物優待券",
    rightsMonths: [5],
  },

  // ── 旅行・ホテル ──────────────────────────────────────────
  {
    id: "9202",
    code: "9202",
    name: "ANA HD",
    brands: ["ANA", "ANAカード", "ANA FESTA", "ANA STORE"],
    categories: ["旅行"],
    lifestyleTags: ["国内旅行派", "飛行機利用頻度高", "マイル派"],
    minShares: 100,
    approxInvestment: 350000,
    annualValue: 8000,
    yieldPercent: 2.3,
    description: "国内線50%割引券1枚(100株・半期ごと1枚、推定片道1回分8,000円相当)",
    rightsMonths: [3, 9],
  },
  {
    id: "9201",
    code: "9201",
    name: "日本航空",
    brands: ["JAL", "JALカード", "JAL PLAZA", "J-AIR"],
    categories: ["旅行"],
    lifestyleTags: ["国内旅行派", "飛行機利用頻度高", "マイル派"],
    minShares: 100,
    approxInvestment: 280000,
    annualValue: 8000,
    yieldPercent: 2.9,
    description: "国内線50%割引券2枚(3月・9月各1枚、推定片道2回分8,000円相当)",
    rightsMonths: [3, 9],
  },
  {
    id: "4681",
    code: "4681",
    name: "リゾートトラスト",
    brands: ["エクシブ", "サンメンバーズ", "ベイコート倶楽部"],
    categories: ["旅行", "ホテル"],
    lifestyleTags: ["国内旅行派", "高級ホテル志向", "ゴルフ好き"],
    minShares: 100,
    approxInvestment: 160000,
    annualValue: 5000,
    yieldPercent: 3.1,
    description: "リゾートホテル・ゴルフ場利用優待(宿泊割引・レストラン優待等、年間推定5,000円相当)",
    rightsMonths: [3, 9],
  },
  {
    id: "9616",
    code: "9616",
    name: "共立メンテナンス",
    brands: ["ドーミーイン", "共立リゾート", "リゾートイン"],
    categories: ["旅行", "ホテル"],
    lifestyleTags: ["国内旅行派", "ビジネス出張", "温泉好き"],
    minShares: 100,
    approxInvestment: 400000,
    annualValue: 6000,
    yieldPercent: 1.5,
    description: "ホテル宿泊優待(朝食付き1泊相当×年2回、推定6,000円相当)",
    rightsMonths: [3],
  },

  // ── エンタメ・映画 ────────────────────────────────────────
  {
    id: "8267",
    code: "8267",
    name: "イオン",
    brands: ["イオン", "マックスバリュ", "イオンモール", "イオンシネマ", "ミニストップ", "まいばすけっと"],
    categories: ["日用品", "エンタメ"],
    lifestyleTags: ["スーパー利用頻度高", "映画好き", "ファミリー外食", "子育て中"],
    minShares: 100,
    approxInvestment: 350000,
    annualValue: 7000,
    yieldPercent: 2.0,
    description: "オーナーズカード(半年間購入額3%キャッシュバック)、映画招待券等(年間推定7,000円相当)",
    rightsMonths: [2, 8],
  },
  {
    id: "9602",
    code: "9602",
    name: "東宝",
    brands: ["TOHOシネマズ", "宝塚歌劇団"],
    categories: ["エンタメ"],
    lifestyleTags: ["映画好き", "エンタメ好き"],
    minShares: 100,
    approxInvestment: 420000,
    annualValue: 8400,
    yieldPercent: 2.0,
    description: "映画観賞券年間4枚(2月・8月各2枚、1枚2,100円換算)",
    rightsMonths: [2, 8],
  },
  {
    id: "4661",
    code: "4661",
    name: "オリエンタルランド",
    brands: ["東京ディズニーランド", "東京ディズニーシー"],
    categories: ["エンタメ"],
    lifestyleTags: ["テーマパーク好き", "ファミリー外食", "子育て中"],
    minShares: 100,
    approxInvestment: 450000,
    annualValue: 9800,
    yieldPercent: 2.2,
    description: "東京ディズニーリゾート1デーパスポート1枚(100株・3月または9月)",
    rightsMonths: [3, 9],
  },

  // ── 日用品・ドラッグストア ─────────────────────────────────
  {
    id: "3141",
    code: "3141",
    name: "ウエルシアHD",
    brands: ["ウエルシア薬局", "ハックドラッグ", "タキヤ", "よどばし薬局"],
    categories: ["日用品"],
    lifestyleTags: ["ドラッグストア高頻度利用", "処方薬利用", "美容・健康意識高"],
    minShares: 100,
    approxInvestment: 230000,
    annualValue: 1500,
    yieldPercent: 0.7,
    description: "WAONポイント1,500ポイント(2月・8月各750ポイント)",
    rightsMonths: [2, 8],
  },
  {
    id: "3088",
    code: "3088",
    name: "マツキヨ ココカラ&カンパニー",
    brands: ["マツモトキヨシ", "ococara fine", "MATSUKIYO"],
    categories: ["日用品"],
    lifestyleTags: ["ドラッグストア高頻度利用", "美容・健康意識高", "化粧品好き"],
    minShares: 100,
    approxInvestment: 250000,
    annualValue: 1500,
    yieldPercent: 0.6,
    description: "優待カード1,500円分(3月・9月各750円分ポイント付与)",
    rightsMonths: [3, 9],
  },
  {
    id: "3349",
    code: "3349",
    name: "コスモス薬品",
    brands: ["コスモス薬品", "ディスカウントドラッグコスモス"],
    categories: ["日用品"],
    lifestyleTags: ["ドラッグストア高頻度利用", "食料品も薬局で購入", "コスパ重視"],
    minShares: 100,
    approxInvestment: 1600000,
    annualValue: 3000,
    yieldPercent: 0.2,
    description: "自社商品500円分×6枚=3,000円分買い物優待",
    rightsMonths: [5],
  },

  // ── スポーツ・アウトドア ──────────────────────────────────
  {
    id: "3028",
    code: "3028",
    name: "アルペン",
    brands: ["アルペン", "スポーツデポ", "ゴルフ5", "ALPEN OUTDOORS"],
    categories: ["スポーツ", "アウトドア"],
    lifestyleTags: ["スポーツ用品購入頻度高", "アウトドア好き", "ゴルフ好き", "キャンプ好き"],
    minShares: 100,
    approxInvestment: 250000,
    annualValue: 5000,
    yieldPercent: 2.0,
    description: "自社グループ5,000円分買い物優待券",
    rightsMonths: [6],
  },
  {
    id: "8281",
    code: "8281",
    name: "ゼビオHD",
    brands: ["ゼビオ", "スーパースポーツゼビオ", "ビクトリア"],
    categories: ["スポーツ"],
    lifestyleTags: ["スポーツ用品購入頻度高", "スポーツ好き"],
    minShares: 100,
    approxInvestment: 120000,
    annualValue: 3000,
    yieldPercent: 2.5,
    description: "買い物優待券3,000円分",
    rightsMonths: [3],
  },
  {
    id: "7514",
    code: "7514",
    name: "ヒマラヤ",
    brands: ["ヒマラヤ", "ヒマラヤスポーツ"],
    categories: ["スポーツ", "アウトドア"],
    lifestyleTags: ["スポーツ用品購入頻度高", "アウトドア好き", "キャンプ好き"],
    minShares: 100,
    approxInvestment: 80000,
    annualValue: 3000,
    yieldPercent: 3.8,
    description: "買い物優待券3,000円分",
    rightsMonths: [8],
  },

  // ── 自動車関連 ────────────────────────────────────────────
  {
    id: "5019",
    code: "5019",
    name: "出光興産",
    brands: ["出光", "apollostation", "シェル"],
    categories: ["自動車関連"],
    lifestyleTags: ["車所有", "ガソリン給油頻度高", "ドライブ好き"],
    minShares: 100,
    approxInvestment: 120000,
    annualValue: 3000,
    yieldPercent: 2.5,
    description: "ガソリン・灯油購入割引カード(2円/L割引、年間推定3,000円相当)",
    rightsMonths: [3],
  },
  {
    id: "5020",
    code: "5020",
    name: "ENEOS HD",
    brands: ["ENEOS", "ENEOS Dr.Drive"],
    categories: ["自動車関連"],
    lifestyleTags: ["車所有", "ガソリン給油頻度高"],
    minShares: 100,
    approxInvestment: 90000,
    annualValue: 2000,
    yieldPercent: 2.2,
    description: "カタログギフト2,000円相当(100株の場合)",
    rightsMonths: [3],
  },

  // ── 食品 ─────────────────────────────────────────────────
  {
    id: "2897",
    code: "2897",
    name: "日清食品HD",
    brands: ["カップヌードル", "日清チキンラーメン", "日清焼そばU.F.O.", "日清のどん兵衛"],
    categories: ["食品"],
    lifestyleTags: ["自炊派", "コスパ重視", "在宅ワーク"],
    minShares: 100,
    approxInvestment: 550000,
    annualValue: 3000,
    yieldPercent: 0.5,
    description: "自社製品詰め合わせ3,000円相当",
    rightsMonths: [3],
  },
  {
    id: "2802",
    code: "2802",
    name: "味の素",
    brands: ["味の素", "Cook Do", "ほんだし", "クノール", "Ajinomoto"],
    categories: ["食品"],
    lifestyleTags: ["自炊派", "料理好き"],
    minShares: 100,
    approxInvestment: 450000,
    annualValue: 1000,
    yieldPercent: 0.2,
    description: "自社製品詰め合わせ1,000円相当(100株の場合)",
    rightsMonths: [3],
  },
];

export type { Yutai };
